### ISSUE TITLE
Please make your Another Repo Private

### ISSUE THREAD

**Issue by wrystal** [yiyuanliu/c-code#1]
Hi Yiyuan,

I, Hao Wang, am one of the TAs for CMU's storage systems course(https://course.ece.cmu.edu/~ece746/) this semester.

Our class includes a project that requires students to build a FTL using FlashSim. We (including the instructors Greg and George) would want you to make this repository (https://github.com/yiyuanliu/18-746-Storage-System) private and or delete it at the earliest. Doing so would avoid a potential scenario in which a student borrows code from your repository and is penalized for cheating.

We understand that you did not put up this code with the intention to facilitate any cheating. However, we have found that under stress, some students give in to the temptation and use code available online in a moment of weakness. This leads to them being penalized heavily for cheating. We want to remove all such temptations so as to avoid such scenarios.

We would appreciate if you can take down the code at the earliest.

Thanks!
Hao

(Sorry for leaving an issue here but I did not find a way to make an issue in that repo)

**Comment by yiyuanliu** [comment]
Done.
